language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t jiaqiwang18/frontend -f Dockerfile.dev . 

script:
  - docker run -e CI=true jiaqiwang18/frontend npm run test